# Generated by Django 3.2.4 on 2023-05-09 14:31

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstr2afiles',
            name='file',
            field=models.FileField(upload_to='Gstr2aMergeExcel/', validators=[core.validators.ExcelFileValidator()]),
        ),
    ]
