# Generated by Django 4.2 on 2023-05-10 04:26

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gst', '0002_alter_gstr2afiles_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gstr2bMergeExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gstr2bFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Gstr2bMergeExcel/', validators=[core.validators.ExcelFileValidator()])),
                ('gstr_2b_merge_excel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gst.gstr2bmergeexcel')),
            ],
        ),
    ]
