# Generated by Django 4.2 on 2023-05-10 05:32

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gst', '0003_gstr2bmergeexcel_gstr2bfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gstr1JsonToExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='Gstr1JsonToExcel/', validators=[core.validators.ExcelFileValidator()])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
