# Generated by Django 4.2 on 2023-05-10 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gst', '0004_gstr1jsontoexcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstr1jsontoexcel',
            name='file',
            field=models.FileField(upload_to='Gstr1JsonToExcel/'),
        ),
        migrations.CreateModel(
            name='Gstr2bJsonToExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='Gstr2bJsonToExcel/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
