




R2A_B2B_COL_MAPPING={
    'Unnamed: 0': 'GSTIN_of_Supplier', 
    'Unnamed: 1': 'Trade_Name_of_Supplier', 
    'Invoice number': 'Final_Invoice_CNDN_No', 
    'Invoice type': 'Final_Inv_CNDN_Type', 
    'Invoice Date': 'Final_Invoice_CNDN_Date', 
    'Invoice Value (₹)': 'Invoice_CNDN_Value', 
    'Unnamed: 6': 'Place_Of_Supply', 
    'Unnamed: 7': 'Supply_Attract_Reverse_Charge', 
    'Unnamed: 8': 'Tax_Rate', 
    'Unnamed: 9': 'Taxable_Value', 
    'Integrated Tax  (₹)': 'IGST_Amount', 
    'Central Tax (₹)': 'CGST_Amount', 
    'State/UT tax (₹)': 'SGST_Amount', 
    'Cess  (₹)': 'Cess_Amount', 
    'Unnamed: 14': 'GSTR_1_5_Filing_Status', 
    'Unnamed: 15': 'Supplier_Filing_Date', 
    'Unnamed: 16': 'Supplier_Filing_Period', 
    'Unnamed: 17': 'GSTR_3B_Filing_Status', 
    'Unnamed: 18': 'Amendment_made_if_any', 
    'Unnamed: 19': 'Tax_Period_in_which_Amended', 
    'Unnamed: 20': 'Effective_date_of_cancellation', 
    'Unnamed: 21': 'Source_Type', 
    'Unnamed: 22': 'IRN', 
    'Unnamed: 23': 'IRN_Generate_Date'
}


R2A_B2BA_COL_MAPPING={
    'Unnamed: 0': 'Initial_Inv_CNDN_No',
    'Unnamed: 1': 'Initial_Inv_CNDN_Date',
    'Unnamed: 2': 'GSTIN_of_Supplier',
    'Unnamed: 3': 'Trade_Name_of_Supplier',
    'Invoice type': 'Final_Inv_CNDN_Type',
    'Invoice number': 'Final_Invoice_CNDN_No',
    'Invoice Date': 'Final_Invoice_CNDN_Date',
    'Invoice Value (₹)': 'Invoice_CNDN_Value',
    'Unnamed: 8': 'Place_Of_Supply',
    'Unnamed: 9': 'Supply_Attract_Reverse_Charge',
    'Unnamed: 10': 'Tax_Rate',
    'Unnamed: 11': 'Taxable_Value',
    'Integrated Tax  (₹)': 'IGST_Amount',
    'Central Tax (₹)': 'CGST_Amount',
    'State/UT tax (₹)': 'SGST_Amount',
    'Cess  (₹)': 'Cess_Amount',
    'Unnamed: 16': 'GSTR_1_5_Filing_Status',
    'Unnamed: 17': 'Supplier_Filing_Date',
    'Unnamed: 18': 'Supplier_Filing_Period',
    'Unnamed: 19': 'GSTR_3B_Filing_Status',
    'Unnamed: 20': 'Effective_date_of_cancellation',
    'Unnamed: 21': 'Amendment_made_if_any',
    'Unnamed: 22': 'Original_tax_period_in_which_reported'
}


R2A_CDNR_COL_MAPPING={
    'Unnamed: 0': 'GSTIN_of_Supplier',
    'Unnamed: 1': 'Trade_Name_of_Supplier',
    'Note type': 'Final_Inv_CNDN_Type',
    'Note number': 'Final_Invoice_CNDN_No',
    'Note Supply type ': 'Final_Note_Supply_Type',
    'Note  date': 'Final_Invoice_CNDN_Date',
    'Note Value (₹)': 'Invoice_CNDN_Value',
    'Unnamed: 7': 'Place_Of_Supply',
    'Unnamed: 8': 'Supply_Attract_Reverse_Charge',
    'Unnamed: 9': 'Tax_Rate',
    'Unnamed: 10': 'Taxable_Value',
    'Integrated Tax (₹)': 'IGST_Amount',
    'Central Tax (₹)': 'CGST_Amount',
    'State Tax (₹)': 'SGST_Amount',
    'Cess Amount (₹)': 'Cess_Amount',
    'Unnamed: 15': 'GSTR_1_5_Filing_Status',
    'Unnamed: 16': 'Supplier_Filing_Date',
    'Unnamed: 17': 'Supplier_Filing_Period',
    'Unnamed: 18': 'GSTR_3B_Filing_Status',
    'Unnamed: 19': 'Amendment_made_if_any',
    'Unnamed: 20': 'Tax_Period_in_which_Amended',
    'Unnamed: 21': 'Effective_date_of_cancellation',
    'Unnamed: 22': 'Source_Type',
    'Unnamed: 23': 'IRN',
    'Unnamed: 24': 'IRN_Generate_Date'
}


R2A_CDNRA_COL_MAPPING={
    'Unnamed: 0': 'Initial_Note_Supply_Type',
    'Unnamed: 1': 'Initial_Inv_CNDN_No',
    'Unnamed: 2': 'Initial_Inv_CNDN_Date',
    'Unnamed: 3': 'GSTIN_of_Supplier',
    'Unnamed: 4': 'Trade_Name_of_Supplier',
    'Note type': 'Final_Inv_CNDN_Type',
    'Note Number ': 'Final_Invoice_CNDN_No',
    'Note Supply type ': 'Final_Note_Supply_Type',
    'Note date': 'Final_Invoice_CNDN_Date',
    'Note Value (₹)': 'Invoice_CNDN_Value',
    'Unnamed: 10': 'Place_Of_Supply',
    'Unnamed: 11': 'Supply_Attract_Reverse_Charge',
    'Unnamed: 12': 'Tax_Rate',
    'Unnamed: 13': 'Taxable_Value',
    'Integrated Tax (₹)': 'IGST_Amount',
    'Central Tax (₹)': 'CGST_Amount',
    'State Tax (₹)': 'SGST_Amount',
    'Cess Amount (₹)': 'Cess_Amount',
    'Unnamed: 18': 'GSTR_1_5_Filing_Status',
    'Unnamed: 19': 'Supplier_Filing_Date',
    'Unnamed: 20': 'Supplier_Filing_Period',
    'Unnamed: 21': 'GSTR_3B_Filing_Status',
    'Unnamed: 22': 'Amendment_made_if_any',
    'Unnamed: 23': 'Original_tax_period_in_which_reported',
    'Unnamed: 24': 'Effective_date_of_cancellation'
}


R1_JSON_COL_MAPPING={"idt":"Final_Invoice_CNDN_Date",
                "val":"Invoice_CNDN_Value",
                "rchrg":"Supply_Attract_Reverse_Charge",
                "itcavl":"ITC_Available",
                "diffprcnt":"Applicable_Percent_TaxRate",
                "pos":"Place_Of_Supply",
                "inv_typ":"Final_Inv_CNDN_Type",
                "inum":"Final_Invoice_CNDN_No",
                "rsn":"Reason",
                "samt":"SGST_Amount",
                "rt":"Tax_Rate",
                "num":"Check_num",
                "txval":"Taxable_Value",
                "camt":"CGST_Amount",
                "csamt":"Cess_Amount",
                "ctin":"GSTIN_of_Customer",
                "iamt":"IGST_Amount",
                "irn":"IRN",
                "cfs":"Counter_Party_Filing_Status",
                "cflag":"Counter_Party_Action",
                "updby":"Uploaded_By",
                "chksum":"Check_Sum",
                "flag":"Tax_Payer_Action",
                "irngendate":"IRN_Generate_Date",
                "srctyp":"Source_Type",
                "rtnprd":"GSTR2B_Period",
                "gstin":"Recipient_GSTIN",
                "Json File Name":"JSON_Source_File",
                "typ":"Final_Inv_CNDN_Type",
                "sply_ty":"Supply_Type",
                "nt_dt":"Final_Invoice_CNDN_Date",
                "nt_num":"Final_Invoice_CNDN_No",
                "d_flag":"d_flag",
                "exp_typ":"Final_Inv_CNDN_Type",
                "File_Name":"Source_Excel_File"}


R2B_B2B_COL_MAPPING={'Goods and Services Tax  - GSTR-2B':'GSTIN_of_Supplier',
                           'Unnamed: 1':'Trade_Name_of_Supplier',
                           'Unnamed: 2':'Final_Invoice_CNDN_No',
                           'Unnamed: 3':'Final_Inv_CNDN_Type',
                           'Unnamed: 4':'Final_Invoice_CNDN_Date',
                           'Unnamed: 5':'Invoice_CNDN_Value',
                           'Unnamed: 6':'Place_Of_Supply',
                           'Unnamed: 7':'Supply_Attract_Reverse_Charge',
                           'Unnamed: 8':'Tax_Rate',
                           'Unnamed: 9':'Taxable_Value',
                           'Unnamed: 10':'IGST_Amount',
                           'Unnamed: 11':'CGST_Amount',
                           'Unnamed: 12':'SGST_Amount',
                           'Unnamed: 13':'Cess_Amount',
                           'Unnamed: 14':'Supplier_Filing_Period',
                           'Unnamed: 15':'Supplier_Filing_Date',
                           'Unnamed: 16':'ITC_Available',
                           'Unnamed: 17':'Reason',
                           'Unnamed: 18':'Applicable_Percent_TaxRate',
                           'Unnamed: 19':'Source_Type',
                           'Unnamed: 20':'IRN',
                           'Unnamed: 21':'IRN_Generate_Date'}


R2B_B2BA_COL_MAPPING={ 'Goods and Services Tax  - GSTR-2B':'Initial_Inv_CNDN_Num',
                            'Unnamed: 1':'Initial_Inv_CNDN_Date',
                            'Unnamed: 2':'GSTIN_of_Supplier',
                            'Unnamed: 3':'Trade_Name_of_Supplier',
                            'Unnamed: 4':'Final_Invoice_CNDN_No',
                            'Unnamed: 5':'Final_Inv_CNDN_Type',
                            'Unnamed: 6':'Final_Invoice_CNDN_Date',
                            'Unnamed: 7':'Invoice_CNDN_Value',
                            'Unnamed: 8':'Place_Of_Supply',
                            'Unnamed: 9':'Supply_Attract_Reverse_Charge',
                            'Unnamed: 10':'Tax_Rate',
                            'Unnamed: 11':'Taxable_Value',
                            'Unnamed: 12':'IGST_Amount',
                            'Unnamed: 13':'CGST_Amount',
                            'Unnamed: 14':'SGST_Amount',
                            'Unnamed: 15':'Cess_Amount',
                            'Unnamed: 16':'Supplier_Filing_Period',
                            'Unnamed: 17':'Supplier_Filing_Date',
                            'Unnamed: 18':'ITC_Available',
                            'Unnamed: 19':'Reason',
                            'Unnamed: 20':'Applicable_Percent_TaxRate'}



R2B_CDNR_COL_MAPPING={ 'Goods and Services Tax  - GSTR-2B':'GSTIN_of_Supplier',
                            'Unnamed: 1':'Trade_Name_of_Supplier',
                            'Unnamed: 2':'Final_Invoice_CNDN_No',
                            'Unnamed: 3':'Final_Inv_CNDN_Type',
                            'Unnamed: 4':'Note_Supply_Type',
                            'Unnamed: 5':'Final_Invoice_CNDN_Date',
                            'Unnamed: 6':'Invoice_CNDN_Value',
                            'Unnamed: 7':'Place_Of_Supply',
                            'Unnamed: 8':'Supply_Attract_Reverse_Charge',
                            'Unnamed: 9':'Tax_Rate',
                            'Unnamed: 10':'Taxable_Value',
                            'Unnamed: 11':'IGST_Amount',
                            'Unnamed: 12':'CGST_Amount',
                            'Unnamed: 13':'SGST_Amount',
                            'Unnamed: 14':'Cess_Amount',
                            'Unnamed: 15':'Supplier_Filing_Period',
                            'Unnamed: 16':'Supplier_Filing_Date',
                            'Unnamed: 17':'ITC_Available',
                            'Unnamed: 18':'Reason',
                            'Unnamed: 19':'Applicable_Percent_TaxRate',
                            'Unnamed: 20':'Source_Type',
                            'Unnamed: 21':'IRN',
                            'Unnamed: 22':'IRN_Generate_Date'}



R2B_CDNRA_COL_MAPPING={ 'Goods and Services Tax  - GSTR-2B':'Initial_Inv_CNDN_Type',
                            'Unnamed: 1':'Initial_Inv_CNDN_No',
                            'Unnamed: 2':'Initial_Inv_CNDN_Date',
                            'Unnamed: 3':'GSTIN_of_Supplier',
                            'Unnamed: 4':'Trade_Name_of_Supplier',
                            'Unnamed: 5':'Final_Invoice_CNDN_No',
                            'Unnamed: 6':'Final_Inv_CNDN_Type',
                            'Unnamed: 7':'Note_Supply_Type',
                            'Unnamed: 8':'Final_Invoice_CNDN_Date',
                            'Unnamed: 9':'Invoice_CNDN_Value',
                            'Unnamed: 10':'Place_Of_Supply',
                            'Unnamed: 11':'Supply_Attract_Reverse_Charge',
                            'Unnamed: 12':'Tax_Rate',
                            'Unnamed: 13':'Taxable_Value',
                            'Unnamed: 14':'IGST_Amount',
                            'Unnamed: 15':'CGST_Amount',
                            'Unnamed: 16':'SGST_Amount',
                            'Unnamed: 17':'Cess_Amount',
                            'Unnamed: 18':'Supplier_Filing_Period',
                            'Unnamed: 19':'Supplier_Filing_Date',
                            'Unnamed: 20':'ITC_Available',
                            'Unnamed: 21':'Reason',
                            'Unnamed: 22':'Applicable_Percent_TaxRate'}

R2B_ISD_COL_MAPPING={ 'Goods and Services Tax  - GSTR-2B':'GSTIN_of_Supplier',
                            'Unnamed: 1':'Trade_Name_of_Supplier',
                            'Unnamed: 2':'Final_Inv_CNDN_Type',
                            'Unnamed: 3':'Final_Invoice_CNDN_No',
                            'Unnamed: 4':'Final_Invoice_CNDN_Date',
                            'Unnamed: 5':'Initial_Inv_CNDN_No',
                            'Unnamed: 6':'Initial_Inv_CNDN_Date',
                            'Unnamed: 7':'IGST_Amount',
                            'Unnamed: 8':'CGST_Amount',
                            'Unnamed: 9':'SGST_Amount',
                            'Unnamed: 10':'Cess_Amount',
                            'Unnamed: 11':'Supplier_Filing_Period',
                            'Unnamed: 12':'Supplier_Filing_Date',
                            'Unnamed: 13':'ITC_Available'}


R2B_IMPG_COL_MAPPING={ 'Goods and Services Tax  - GSTR-2B':'IceGate_Ref_Date',
                            'Unnamed: 1':'Port_Code',
                            'Unnamed: 2':'Bill_Of_Entry_No',
                            'Unnamed: 3':'Record_Date',
                            'Unnamed: 4':'Taxable_Value',
                            'Unnamed: 5':'IGST_Amount',
                            'Unnamed: 6':'Cess_Amount',
                            'Unnamed: 7':'Amended_Y_N'}


R2B_JSON_COL_MAPPING={"dt":"Final_Invoice_CNDN_Date",
                "val":"Invoice_CNDN_Value",
                "rev":"Supply_Attract_Reverse_Charge",
                "itcavl":"ITC_Available",
                "diffprcnt":"Applicable_Percent_TaxRate",
                "pos":"Place_Of_Supply",
                "typ":"Final_Inv_CNDN_Type",
                "inum":"Final_Invoice_CNDN_No",
                "rsn":"Reason",
                "sgst":"SGST_Amount",
                "rt":"Tax_Rate",
                "num":"Check_num",
                "txval":"Taxable_Value",
                "cgst":"CGST_Amount",
                "cess":"Cess_Amount",
                "trdnm":"Trade_Name_of_Supplier",
                "supfildt":"Supplier_Filing_Date",
                "supprd":"Supplier_Filing_Period",
                "ctin":"GSTIN_of_Supplier",
                "igst":"IGST_Amount",
                "irn":"IRN",
                "irngendate":"IRN_Generate_Date",
                "srctyp":"Source_Type",
                "GSTR2B-Table":"GSTR2B-Table",
                "rtnprd":"GSTR2B_Period",
                "gstin":"Recipient_GSTIN",
                "Json File Name":"JSON_Source_File",
                "File_Name":"Source_Excel_File",
                "oinum":"Initial_Inv_CNDN_No",
                "oidt":"Initial_Inv_CNDN_Date",
                "ntnum":"Final_Invoice_CNDN_No",
                "suptyp":"Note_Supply_Type",
                "ontdt":"Initial_Inv_CNDN_Date",
                "onttyp":"Initial_Inv_CNDN_Type",
                "ontnum":"Initial_Inv_CNDN_No",
                "docnum":"Final_Invoice_CNDN_No",
                "itcelg":"ITC_Available",
                "doctyp":"Final_Inv_CNDN_Type",
                "docdt":"Final_Invoice_CNDN_Date",
                "oinvnum":"Initial_Inv_CNDN_No",
                "oinvdt":"Initial_Inv_CNDN_Date",
                "boedt":"Bill_Of_Entry_Date",
                "isamd":"Amended_Y_N",
                "recdt":"Record_Date",
                "refdt":"IceGate_Ref_Date",
                "boenum":"Bill_Of_Entry_No",
                "portcode":"Port_Code"}